### ISSUE TITLE
VS 2013: Package Manager Console - Install-Package Error

### ISSUE THREAD

**Issue by radleta** [mhowlett/LightweightInfluxDb#1]
I'm trying to install the Nuget package and receive the following message. I ensured I updated to the latest Nuget package. Any ideas?

```
PM> Install-Package LightweightInfluxDb
Install-Package : ZIP archive contains unsupported data structures.
At line:1 char:16
+ Install-Package <<<<  LightweightInfluxDb
    + CategoryInfo          : NotSpecified: (:) [Install-Package], NotSupportedException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

**Comment by mhowlett** [comment]
Thanks - good to know there is a problem. I can confirm it works for me on all platforms (VS2015 on windows) in an asp.net 5 console app (i.e. using dnx). It could be something to do with where i packaged it up, which was not on windows. I'll take a look at it probably later today. For now, the library should all work in VS2013 if you just create a new project yourself out of the cs files.

**Comment by radleta** [comment]
No worries! I just wanted to pass it along.

**Comment by mhowlett** [comment]
The latest nuget package (1.7) was created using dnu pack on windows. Be good to know if this is working in VS2013.

**Comment by radleta** [comment]
Good news and bad news. I was able to get further with the install but it then complained about .NET 4.5 compatibility.

```
PM> Install-Package LightweightInfluxDb
Installing 'LightweightInfluxDb 1.7.0'.
Successfully installed 'LightweightInfluxDb 1.7.0'.
Adding 'LightweightInfluxDb 1.7.0' to Web.Track.
Uninstalling 'LightweightInfluxDb 1.7.0'.
Successfully uninstalled 'LightweightInfluxDb 1.7.0'.
Install failed. Rolling back...
Install-Package : Could not install package 'LightweightInfluxDb 1.7.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more inf
ormation, contact the package author.
At line:1 char:16
+ Install-Package <<<<  LightweightInfluxDb
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

**Comment by mhowlett** [comment]
i think this is because the project file specifies dnx451. It looks like you only have .net 4.5 installed and I'm guessing it will work if you install .net 4.5.1 or 4.5.2. The reason for targeting dnx451 is that all the example code does - I'm guessing there is a good reason why this is not a lower version, though I don't know what that is.

**Comment by radleta** [comment]
It looks like a separate issue. I'm closing this one as fixed. Thanks!
